global:
  scrape_interval: 15s # Par défaut, scrape toutes les 15 secondes.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    # Nécessite de lancer cAdvisor sur l'hôte ou d'utiliser un conteneur séparé
    # En environnement Docker-Compose, Prometheus peut collecter les métriques de lui-même et des autres.
    # Pour les conteneurs (cAdvisor) et l'hôte (Node-Exporter), vous devriez les ajouter
    # comme services dans le docker-compose.yml ou les lancer manuellement.
    static_configs:
      - targets: ['cadvisor:8080'] # Exemple, si cAdvisor est dans le réseau

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Pour monitorer les services exposés via Traefik (si ils exposent des métriques)
  - job_name: 'traefik'
    metrics_path: /api/prometheus
    static_configs:
      - targets: ['traefik:8080']

  # Pour monitorer Cassandra (Nécessite un Exporter - non inclus pour la simplicité, mais essentiel)
  # - job_name: 'cassandra'
  #   static_configs:
  #     - targets: ['cassandra1:9103', 'cassandra2:9103', 'cassandra3:9103']