global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:9042']

  - job_name: 'glpi'
    static_configs:
      - targets: ['glpi:80'] # Assuming GLPI exposes metrics on port 80, this might need adjustment

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000'] # Assuming Grafana exposes metrics on port 3000, this might need adjustment

