---
- name: "PRA: Déploiement de l'infrastructure K8s sur le Site B"
  hosts: all_nodes
  become: yes
  gather_facts: yes

  tasks:
    # Récupérer les facts (nécessaire pour la suite)
    - setup:

    # 1. Installer Docker et les pré-requis du système
    - name: "Mettre à jour le système et installer les dépendances"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - apt-transport-https
        - curl
        - kubelet
        - kubeadm
        - kubectl

    # 2. Exécuter le rôle d'installation de Kubernetes
    - name: "Inclure le rôle d'installation K8s"
      ansible.builtin.include_role:
        name: k8s_setup

    # 3. Exécuter le rôle d'installation du Monitoring
    - name: "Inclure le rôle d'installation du Monitoring (Prometheus/Grafana)"
      ansible.builtin.include_role:
        name: monitoring_tools